package top.mitrecx.dazhixianxian.dal.entity;

import java.io.Serializable;

public class DzUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.id
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.login_name
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.username
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.password
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.email
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.phone
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.status
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.delete_flag
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.created_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private Long createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.last_updated_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private Long lastUpdatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dz_user.last_login_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private Long lastLoginAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dz_user
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.id
     *
     * @return the value of dz_user.id
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.id
     *
     * @param id the value for dz_user.id
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.login_name
     *
     * @return the value of dz_user.login_name
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.login_name
     *
     * @param loginName the value for dz_user.login_name
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.username
     *
     * @return the value of dz_user.username
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.username
     *
     * @param username the value for dz_user.username
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.password
     *
     * @return the value of dz_user.password
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.password
     *
     * @param password the value for dz_user.password
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.email
     *
     * @return the value of dz_user.email
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.email
     *
     * @param email the value for dz_user.email
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.phone
     *
     * @return the value of dz_user.phone
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.phone
     *
     * @param phone the value for dz_user.phone
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.status
     *
     * @return the value of dz_user.status
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.status
     *
     * @param status the value for dz_user.status
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.delete_flag
     *
     * @return the value of dz_user.delete_flag
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.delete_flag
     *
     * @param deleteFlag the value for dz_user.delete_flag
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.created_at
     *
     * @return the value of dz_user.created_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public Long getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.created_at
     *
     * @param createdAt the value for dz_user.created_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setCreatedAt(Long createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.last_updated_at
     *
     * @return the value of dz_user.last_updated_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public Long getLastUpdatedAt() {
        return lastUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.last_updated_at
     *
     * @param lastUpdatedAt the value for dz_user.last_updated_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setLastUpdatedAt(Long lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dz_user.last_login_at
     *
     * @return the value of dz_user.last_login_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public Long getLastLoginAt() {
        return lastLoginAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dz_user.last_login_at
     *
     * @param lastLoginAt the value for dz_user.last_login_at
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    public void setLastLoginAt(Long lastLoginAt) {
        this.lastLoginAt = lastLoginAt;
    }
}