server:
  port: 8001
  #port: 443
  #ssl:
  #  key-store-password: 1ozrddug
  #  key-store-type: JKS
  #  key-store: classpath:mitrecx.top.jks
  #  key-alias: tomcat
  # 设置会话超时时间（单位：秒）
  servlet:
    session:
      timeout: 1800


logging:
  level:
    root: INFO
#    org.mybatis: DEBUG
#    org.apache.ibatis: DEBUG

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/dazhi
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/ext/*.xml
#    type-aliases-package: com.example.model

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: "大智闲闲接口文档"
    email: mitrecx@163.com
    concat: cx
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - top.mitrecx.dazhixianxian.controller

