package top.mitrecx.dazhixianxian.dal.dao;

import top.mitrecx.dazhixianxian.dal.entity.DzUser;

public interface DzUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    int insert(DzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    int insertSelective(DzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    DzUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    int updateByPrimaryKeySelective(DzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Mon Jan 15 10:15:39 CST 2024
     */
    int updateByPrimaryKey(DzUser record);
}