package top.mitrecx.dazhixianxian.mapper;

import top.mitrecx.dazhixianxian.domain.po.DzUser;

public interface DzUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Wed Jan 31 10:24:55 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Wed Jan 31 10:24:55 CST 2024
     */
    int insert(DzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Wed Jan 31 10:24:55 CST 2024
     */
    int insertSelective(DzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Wed Jan 31 10:24:55 CST 2024
     */
    DzUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Wed Jan 31 10:24:55 CST 2024
     */
    int updateByPrimaryKeySelective(DzUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dz_user
     *
     * @mbg.generated Wed Jan 31 10:24:55 CST 2024
     */
    int updateByPrimaryKey(DzUser record);
}